### ISSUE TITLE
Image of heart shaped icon (to be added in your favourites list) is missing sir

### ISSUE THREAD

**Issue by Deepu2104** [jonasschmedtmann/complete-javascript-course#14]
` <div class="likes">
                <div class="likes__field">
                    <svg class="likes__icon">
                        <use href="img/icons.svg#icon-heart"></use>
                    </svg>
                </div>`

**Comment by Deepu2104** [comment]
<div class="likes">
                <div class="likes__field">
                    <svg class="likes__icon">
                        <use href="img/icons.svg#icon-heart"></use>
                    </svg>
                </div>

**Comment by jonasschmedtmann** [comment]
Please post issues like this one to the course Q&A.

**Comment by Deepu2104** [comment]
Thanks for your reply sir. I will surely do it sir..
