### ISSUE TITLE
Final app.js Code not Running Properly

### ISSUE THREAD

**Issue by Gutzy55** [jonasschmedtmann/complete-javascript-course#15]
Hello,

There is an issue when it comes to the data structure (array) of the incomes and expenses. It is causing an error when trying to account for the length being zero. I copied your final version of code to see if it would run and it is not. Please see below for reference.

Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.addItem (app.js:65)
    at HTMLButtonElement.ctrlAddItem (app.js:410)

Thanks,
Jeremy

**Comment by jonasschmedtmann** [comment]
Please post issues like this one to the course Q&A, this repo is really just for hosting the files.
Jonas

**Comment by Gutzy55** [comment]
Thanks already did and someone helped out.
Jeremy
