### ISSUE TITLE
Forkify App is not working properly 

### ISSUE THREAD

**Issue by Ahmad-Mansour** [jonasschmedtmann/complete-javascript-course#16]
Good day Mr. Jonas, 

I've been playing around with forkify app to see the final project we're gonna be building. Unfortunately, it's not operating as it should be. Probably because they updated their API at Food2Fork.com. 

Amazing course by the way! Thanks.

**Comment by jonasschmedtmann** [comment]
What they changed was the API limit, you can only make 50 calls per day now, and that runs out very quickly. At some points in the day, after they reset it, it starts working again :)

I will make that more clear in the error message!

**Comment by sneh5119** [comment]
i am debugging the code in the terminal of package.json with npm run start but it is showing the initial stage of project.
i have completed the project but it is not fetching the data and code .Could you tell why is this happening?

**Comment by jonasschmedtmann** [comment]
Hi sneh,

Please post this question in the official course Q&A on Udemy, this is the central place for all questions, and makes this information available to all students of the course :)

--
Jonas Schmedtmann
jonas.io<http://jonas.io> / @jonasschmedtman<https://twitter.com/jonasschmedtman>

On July 12, 2020 at 12:21 PM, sneh5119 (notifications@github.com<mailto:notifications@github.com>) wrote:
i am debugging the code in the terminal of package.json with npm run start but it is showing the initial stage of project.
i have completed the project but it is not fetching the data and code .Could you tell why is this happening?

**Comment by sneh5119** [comment]
hello, im sorry if i disturbed you😌. But my problem is fixed now and a big
thank you to you for creating such amazing course.🤗

**Comment by jonasschmedtmann** [comment]
Hi Sneh,

No problem, I'm glad it's solved 😀

--
Jonas Schmedtmann
jonas.io<http://jonas.io> / @jonasschmedtman<https://twitter.com/jonasschmedtman>

On July 12, 2020 at 10:53 PM, sneh5119 (notifications@github.com<mailto:notifications@github.com>) wrote:
hello, im sorry if i disturbed you😌. But my problem is fixed now and a big
thank you to you for creating such amazing course.🤗

**Comment by Zucci-Daniel** [comment]
Hello!, i'm zucci, i'm always getting this message 'error proccessing recipe' and i'm freezed in the BUILDING THE RECIPE MODEL PART2, i've double watched the vid to see if i made any errors, buh i can't seem to find any... in the console, i don't see any error expect that it is'nt working or showing as yours in this stage......pls help!!

**Comment by mohamed-hossam1** [comment]
The API is not working
