### ISSUE TITLE
failure to load resource

### ISSUE THREAD

**Issue by jerryon92** [jonasschmedtmann/complete-javascript-course#18]
I am having challenge with the first lesson. 
(hello world challenge)

I have some errors when i try to run it on internet explorer .

**Comment by jerryon92** [comment]
Before I enter the java script code in the script.js file, bracket gives me an "ESLint terminates with error timeout" error.

And after the

**Comment by jonasschmedtmann** [comment]
Please post this in the course Q&A for a more detailed response. Anyway, that brackets ESLint error has nothing to do with the code itself, the code will work just fine. if it doesn't, there is a problem in your code. Please ask for help on the Q&A section.
