### ISSUE TITLE
Autocomplete js extension for Brackets

### ISSUE THREAD

**Issue by thealiraza** [jonasschmedtmann/complete-javascript-course#2]
Hello Jonas,
I am a great fan and student of you from Pakistan. Actually, I have installed Brackets for HTML, CSS and JS. But, I am unable to enable the autocomplete option for JS. Which extension or way, you can recommend solving this issue.
Thank you.

**Comment by jonasschmedtmann** [comment]
Autocomplete should work for all languages out-of-the-box in Brackets, no extensions needed. Make sure you save the file as .js
