### ISSUE TITLE
I can't seem to download the course file. Do you have a guide on how to do so?

### ISSUE THREAD

**Issue by ErmiasRegassa** [jonasschmedtmann/complete-javascript-course#20]

**Comment by jonasschmedtmann** [comment]
On the main repo page, please just click "Download ZIP", like in the image.

![image](https://user-images.githubusercontent.com/18718850/55495755-80764200-5635-11e9-9954-ad4520060e19.png)

**Comment by Sid9nov** [comment]
I  not able to found any clone or download button so please help me out

**Comment by jonasschmedtmann** [comment]
It is literally where the image above shows you. It's just that green button

**Comment by ujjwalsb** [comment]
Seriously?
go to the main page of the repo and on the right-hand side you will find a green button `clone or download`
