### ISSUE TITLE
Console.log("Test") not working at all on Forkify

### ISSUE THREAD

**Issue by WinnieNg3210** [jonasschmedtmann/complete-javascript-course#216]
I've doubled check the script tag to make sure it's pointing to the controller.js in the src file but it's not working either; My index.html file is also the entry point with default: "index.html" in the package.json file.

Aside from the script tag, would there be another reason why the console wouldn't work?

Also I don't know if it's an issue: but in the dist folder, the name of my files are index.430f....js, not controller.{whatever number}.js like in the video; Would this be an issue down the line? I don't really think the naming of the file should be any issue and the file is bundling the code from controller.js but since this was created when I ran npm, I'm just curious. I've looked through the video multiple times and at this point I don't think I'm missing anything.

There was only one other person who had the same issue as mine for the same lecture but the question wasn't answered.

![Screen Shot 2021-12-07 at 10 03 54 AM](https://user-images.githubusercontent.com/32966351/145058534-149b6153-408e-43bc-a50a-665ca1392e8e.jpg)
![Screen Shot 2021-12-07 at 10 04 11 AM](https://user-images.githubusercontent.com/32966351/145058538-6dc35b31-d7e6-4d6c-b75c-32f335b3e6e5.jpg)
![Screen Shot 2021-12-07 at 10 12 20 AM](https://user-images.githubusercontent.com/32966351/145058540-f4fb0274-43f3-4d58-8fac-ceac032fbcfe.jpg)
![Screen Shot 2021-12-07 at 10 04 20 AM](https://user-images.githubusercontent.com/32966351/145058542-cefec003-1bfa-4972-b326-d37b3f991cc3.jpg)

**Comment by akozdev** [comment]
Hi Winnie
Do you have your app repo on GitHub? Can you share the link? I'll check this

**Comment by WinnieNg3210** [comment]
Here's the repo: https://github.com/WinnieNg3210/forkifyApp

**Comment by WinnieNg3210** [comment]
Hi! I found out the fix to the issue: it was to add module="type" to the script tag. I had an issue with the browser script import so I added the 'module=type' to the script but it also ended up fixing the console issue as well.
