### ISSUE TITLE
Computer crashed database

### ISSUE THREAD

**Issue by Justinhaosheng** [jonasschmedtmann/complete-javascript-course#24]
I forgot how to open the teaching part of the course. I found my script.js but can't find the teaching part. Could you please instruct me on how to reach it? I would greatly appreciate it.

**Comment by jonasschmedtmann** [comment]
What do you mean by "teaching part"? My final version of the code? It's inside of each of the project folders, along with the starter code

**Comment by Justinhaosheng** [comment]
Sorry for the confusion, I meant the video teaching part but of the courses, but I found them. Sorry again.
