### ISSUE TITLE
Javascrpit

### ISSUE THREAD

**Issue by badman555** [jonasschmedtmann/complete-javascript-course#27]
Consle is not defined errors in eslint (brackets ide)
![15604258791074074830575158717181](https://user-images.githubusercontent.com/51786167/59429666-e03f5500-8dfd-11e9-9f70-3987c5a66509.jpg)

**Comment by j10cr** [comment]
Remove capital "C" on console.log()

**Comment by jonasschmedtmann** [comment]
These are not errors in your code, and you can simply ignore them (they just come from so-called linters that are not correctly set up).
