### ISSUE TITLE
Advanced JS objects and functions Not Running

### ISSUE THREAD

**Issue by HarshitaSing** [jonasschmedtmann/complete-javascript-course#30]
The final code is not running on my browser. Also there is no error in the console.
i have added the files. Please help. 

[Objects and functions.zip](https://github.com/jonasschmedtmann/complete-javascript-course/files/3318358/Objects.and.functions.zip)

**Comment by akozdev** [comment]
The js file you provided doesn't contain any code. If it's an issue with your code (and not the project itself), please post your question in the Q&A section of the JavaScript course

**Comment by HarshitaSing** [comment]
> The js file you provided doesn't contain any code. If it's an issue with your code (and not the project itself), please post your question in the Q&A section of the JavaScript course

YA it worked . Thanku .
