### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Jrm088** [jonasschmedtmann/complete-javascript-course#309]
Hi, I'm new to Github so excuse me if missing something. I've tried to download the required files for this course. The only items in each of the files is a starter and final folder.  When i open the stater or final  files, it opens a browser that says "JavaScript fundamentals 1". I dont see any other course material.

**Comment by akozdev** [comment]
Hi Joe
The _starter_ directory contains only the files needed to start, and the _final_ directory contains the final files after each section.
In case of _01-Fundamentals-Part-1_, the _final_ directory should also contain the _script.js_ file with the code written in the first section of the course. You can open it in the code editor of your choice.

**Comment by Jrm088** [comment]
Thank you!
