### ISSUE TITLE
Cannot Open File and HTML doesn't work 

### ISSUE THREAD

**Issue by ChickenGunner** [jonasschmedtmann/complete-javascript-course#35]
Hello. I have a problem which I need help with. I am following and watching @jonasschmedtmann full javascript course and everything was nice. I downloaded the ZIP file and it works fine when I open it in files. But when I try to open it Brackets, it doesn't show the index in the file. So I manually opened it with "Open files". I followed the course and everything was okay until we typed our first line of code and then opened the index.html. It wouldn't show the code in the console. I attached some pictures for you to see.

![Desktop_190925_1329](https://user-images.githubusercontent.com/55789427/65593404-1366b800-df99-11e9-8750-467baefbf0dd.png)
![Desktop_190925_1329_1](https://user-images.githubusercontent.com/55789427/65593405-1366b800-df99-11e9-94f7-f0f5fc551e63.png)
![Desktop_190925_1329_2](https://user-images.githubusercontent.com/55789427/65593407-1366b800-df99-11e9-9b56-935e4c4a2c5e.png)
![Desktop_190925_1330](https://user-images.githubusercontent.com/55789427/65593409-1366b800-df99-11e9-80e4-7e6b063fe5cb.png)
![Desktop_190925_1332](https://user-images.githubusercontent.com/55789427/65593410-13ff4e80-df99-11e9-93c1-d43451c3bb16.png)

**Comment by jonasschmedtmann** [comment]
Haven't used Brackets in a while (I use VS Code now), but all you have to do is to open the starter folder, not the file itself. That folder will then be your project folder, containing index.html without any JS code in it, just the HTML code which produces the result you have in the image. From there, you will have to add the JS code as instructed in the video.

**Comment by ChickenGunner** [comment]
> Haven't used Brackets in a while (I use VS Code now), but all you have to do is to open the starter folder, not the file itself. That folder will then be your project folder, containing index.html without any JS code in it, just the HTML code which produces the result you have in the image. From there, you will have to add the JS code as instructed in the video.

Thank You! I got that but my code doesn't show in the html. Why?

**Comment by jonasschmedtmann** [comment]
That's hard to tell. Where does the code not show? What does your code look like?

**Comment by ChickenGunner** [comment]
> That's hard to tell. Where does the code not show? What does your code look like?

It doesn't show in the console of the html once I finish typing Hello World. I copied what you did in your video but my code doesn't show. I'm giving you a hard time... Sorry.

**Comment by jonasschmedtmann** [comment]
Can you post a screenshot of the code itself? That must be where the error is

**Comment by ChickenGunner** [comment]
ok sure.

**Comment by ChickenGunner** [comment]
[image: Desktop_190925_1711.png]
[image: Desktop_190925_1712.png]

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jonasschmedtmann** [comment]
Your images are not visible...

**Comment by ChickenGunner** [comment]
> Your images are not visible...

I replied via gmail. Sorry for giving you a hard time... I really apologize.

**Comment by ChickenGunner** [comment]
> Your images are not visible...

![Desktop_190925_1712](https://user-images.githubusercontent.com/55789427/65666583-a27dd980-e046-11e9-9ca1-545e5b30fcf2.png)
![Desktop_190925_1711](https://user-images.githubusercontent.com/55789427/65666584-a27dd980-e046-11e9-9a0c-384f86297043.png)

**Comment by angularfirst** [comment]
Script tag is outside body. Script tag should be just before ending the
body tag.

**Comment by jonasschmedtmann** [comment]
It looks to me like you're simply not opening the correct file. The one you have opened in Brackets is in the starter folder, but then in Chrome you open index.html straight from the desktop, which should not be the same file. Please do "view page source" and check if the code you wrote in Brackets is actually in the page you're loading.

**Comment by ChickenGunner** [comment]
Ooohh! Thank you very much!! I appreciate it!

**Comment by ChickenGunner** [comment]
> It looks to me like you're simply not opening the correct file. The one you have opened in Brackets is in the starter folder, but then in Chrome you open index.html straight from the desktop, which should not be the same file. Please do "view page source" and check if the code you wrote in Brackets is actually in the page you're loading.

![Desktop_190926_1344](https://user-images.githubusercontent.com/55789427/65682670-111d6000-e064-11e9-9036-e61a5b1a3e2f.png)
![Desktop_190926_1346](https://user-images.githubusercontent.com/55789427/65682672-11b5f680-e064-11e9-927b-0c45a12cbbe3.png)

**Comment by jonasschmedtmann** [comment]
That "console" error is not an error at all, there are tons of posts about this in the course Q&A that you can read. In fact, issues on Github are for real errors in the code, not for fixing mistakes you are making, that's what the course Q&A is for. So in the future, please post issues that you have with the code there.
About this error you're seeing, it's happening because the script.js file is not in the correct folder. Of course, it has to be in the same folder as index.html, so in the starter folder. This is very basic stuff, and it would be best for your learning process to try to debug simple things like this on your own first :)

**Comment by ChickenGunner** [comment]
Ok thank you!
