### ISSUE TITLE
JSLint error - 'console' was used before it was defined 

### ISSUE THREAD

**Issue by asinghal2149** [jonasschmedtmann/complete-javascript-course#38]
JSLint error - 'console' was used before it was defined 
and a 
[errors showing in Javascript.pdf](https://github.com/jonasschmedtmann/complete-javascript-course/files/3656102/errors.showing.in.Javascript.pdf)
host of other errors in ESLint

**Comment by ChickenGunner** [comment]
> JSLint error - 'console' was used before it was defined
> and a
> [errors showing in Javascript.pdf](https://github.com/jonasschmedtmann/complete-javascript-course/files/3656102/errors.showing.in.Javascript.pdf)
> host of other errors in ESLint

I get this same problem! I'm not able to put anything in the console because of these errors. I've been trying to figure this out but there are no solutions... Please help. @jonasschmedtmann

**Comment by jonasschmedtmann** [comment]
As I mentioned many times in the course Q&A, this is **not an error**. Nothing will stop working because of this. It is simply a problem with ESLint in Brackets (ESLint is a program that checks for coding mistakes, but this is currently not working properly in Brackets).
So if your code doesn't work, **it is not because of this** warning that ESLint shows you. You have some other error that you have to fix instead.

**Comment by LittleChaty** [comment]
Sorry for this topic again, but what happened if my code looks the same as your code. I've made the same steps. 
var firstName = 'John';
console.log(firstName);
Thank you for your understanding and your help!

**Comment by jonasschmedtmann** [comment]
The code is correct, of course. Again, if you see errors or warnings in Brackets, these are NOT errors in your code, please just ignore them.

**Comment by umarbava** [comment]
i am having the same error

**Comment by umarbava** [comment]
enlint is coming console not defined and when i run it 
in chrome it shows error 
GET file:///C:/Users/umarb/Desktop/complete-javascript-course-master/2-JS-basics/starter/script.js net::ERR_FILE_NOT_FOUND

**Comment by jonasschmedtmann** [comment]
Hi Umarbava,

Please post this question in the official course Q&A on Udemy, this is the central place for all questions, and makes this information available to all students of the course :)

--
Jonas Schmedtmann
jonas.io<http://jonas.io> / @jonasschmedtman<https://twitter.com/jonasschmedtman>

On May 22, 2020 at 6:52 PM, umarbava (notifications@github.com<mailto:notifications@github.com>) wrote:

enlint is coming console not defined and when i run it
in chrome it shows error
GET file:///C:/Users/umarb/Desktop/complete-javascript-course-master/2-JS-basics/starter/script.js net::ERR_FILE_NOT_FOUND

**Comment by jonasschmedtmann** [comment]
No, that is not the same error, it's completely different. That error is because you referenced the wrong path to your JS file in your HTML.

**Comment by KaushikGarkoti** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/64689164/84504157-13e6e080-acd9-11ea-8fae-7109139e0346.png)
I am getting these errors

**Comment by iflanagan** [comment]
I have this code in the script.js file 

var firstName = 'John';
console.log(firstName);

var lastName = 'Smith';
var age = 28;

var fullAge = true;
console.log(fullAge);

when I click on the index.html ->right click->inspect and click console I never see any of the js commands being executed...I am using google chrome

**Comment by jonasschmedtmann** [comment]
Hi Imfaus,

Please post this question in the official course Q&A on Udemy, this is the central place for all questions, and makes this information available to all students of the course :)

--
Jonas Schmedtmann
jonas.io<http://jonas.io> / @jonasschmedtman<https://twitter.com/jonasschmedtman>

On August 19, 2020 at 3:42 PM, imfaus (notifications@github.com<mailto:notifications@github.com>) wrote:
I have this code in the script.js file
var firstName = 'John';
console.log(firstName);
var lastName = 'Smith';
var age = 28;
var fullAge = true;
console.log(fullAge);
when I click on the index.html ->right click->inspect and click console I never see any of the js commands being executed...I am using google chrome

**Comment by DrRKSuresh** [comment]
I am also getting the same error

**Comment by Mynajobs** [comment]
I am also getting the same error! but when I run the same code in jsbin it runs successfully and I get my desired output, which indicates that the code is correct but then in brackets it doesn't work!
