### ISSUE TITLE
Forkify API not working

### ISSUE THREAD

**Issue by classic-presh** [jonasschmedtmann/complete-javascript-course#385]
I've been learning with your course, and I find it amazing and all has been going smooth. Everything was fine before I went to bed last night, however, when I woke up this morning to continue with building the Forkify App, it keeps failing to generate data from the Forkify API. I visited the demo site (forkify-v2.netlify.app) and the same issue persisted. Please check kindly look into it.

**Comment by classic-presh** [comment]
I checked again now and it's working again

**Comment by songhetian** [comment]
Can you tell me the latest API address? thanks

**Comment by classic-presh** [comment]
Same as before. Maybe it was some server issue that caused the glitch but everything is fine now.

**Comment by songhetian** [comment]
Is this it https://forkify-api.herokuapp.com/api/v2  Still unable to access Which API address are you currently using

**Comment by classic-presh** [comment]
Yeah still the same
![forkify](https://github.com/jonasschmedtmann/complete-javascript-course/assets/118505563/12a9dd61-4a7a-493a-9394-6a4e2d425f58)

**Comment by classic-presh** [comment]
use the URL minus "...api/"

**Comment by songhetian** [comment]
Hi brother, I can access this API now because my DNS is malfunctioning. Thank you very much

**Comment by classic-presh** [comment]
You're very much welcome bro. Happy coding 🙂
