### ISSUE TITLE
API key is not valid after sending request 

### ISSUE THREAD

**Issue by NIK9102002** [jonasschmedtmann/complete-javascript-course#391]
https://drive.google.com/file/d/1IDRvy2kOdtfC3vwfInKrPnEFrezROOMo/view?usp=share_link

https://drive.google.com/file/d/1g73LTXrH1rKRDHtyszrLleNz9HPtmUML/view?usp=share_link

This are the links for my errors in console

**Comment by akozdev** [comment]
What if you change `Key` (capitalized) to `key` (lowercase) in the _loadRecipe_ function?

**Comment by NIK9102002** [comment]
.
