### ISSUE TITLE
food2fork.com is going to be shutted down

### ISSUE THREAD

**Issue by Sormus95** [jonasschmedtmann/complete-javascript-course#49]
Hi,
It is not an issue yet, but the site food2fork.com is going to be shutted down on November 30th, 2019(Info about it here: https://www.food2fork.com). I know, you have created your own API, but the images are stored on their server, so we won't be able to access them after November 30th.

**Comment by jonasschmedtmann** [comment]
Yeah that’s a good point, I will look into this!

**Comment by Limuthu** [comment]
Then Jonas How we Do that Project?
