### ISSUE TITLE
The API used on the Food Project is Dead.

### ISSUE THREAD

**Issue by chr1974** [jonasschmedtmann/complete-javascript-course#52]
Hi, 
I purchased your course today 15 Dec 2019, and I see that the API food2fork that you used in one of the projects is dead and closed in November this year. So I think it is time to revise the course and use another API to pull data, so the course is up to date. as is now it is not easy to follow that project without a working API.

**Comment by jonasschmedtmann** [comment]
Did you even take a look at the course? I have had a new API for about two months there. There is a text lecture somewhere in this section where I explain how it works. Documentation is also at [https://forkify-api.herokuapp.com/ ](https://forkify-api.herokuapp.com/), but you should also read that text lecture.

**Comment by chr1974** [comment]
Sorry, I only watched your live app and had now data. lol my apologies.
