### ISSUE TITLE
PDF is a corrupted file

### ISSUE THREAD

**Issue by ktdevelops** [jonasschmedtmann/complete-javascript-course#62]
After downloading the pdf, I could not open it. Got an error message

**Comment by SvilenGrandzhan** [comment]
Hi, 
witch pdf file you could not open? I tried them all and it is working fine with me. You may try to download it again and/ or open it with different pdf reader. Let me know if I can help with something else

**Comment by ktdevelops** [comment]
slide-students-c03.pdf was the one I couldn't download. but yes I just retried and it worked.  I think the network at my job was poor yesterday.

Thanks
