### ISSUE TITLE
dependencies alerts in 9-forkify/final/package-lock.json?

### ISSUE THREAD

**Issue by McVenco** [jonasschmedtmann/complete-javascript-course#7]
Hi Jonas,

I just bought your course, and downloaded these source files. I then created my own (new) git repository, and promptly received a number of alerts from Github:

![image](https://user-images.githubusercontent.com/8972182/47454370-55a6d880-d7cf-11e8-973c-45921b63dc94.png)

I haven't checked the source code yet, but maybe some dependencies need to be updated?

Thanks in advance, and I'm eager to start your course right now :-)

**Comment by jonasschmedtmann** [comment]
Hi Eric,

I always leave the code exactly as I show in the videos, including the package.json file. When students follow the project and start downloading the NPM packages on their own, they will receive the most up to date versions.

If you want to update your package.json file to the newest versions, just run npm update --dev

Cheers,

Jonas

On Oct 24, 2018, at 8:02 PM, Eric Vonk <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jonas,

I just bought your course, and downloaded these source files. I then created my own (new) git repository, and promptly received a number of alerts from Github:

[image]<https://user-images.githubusercontent.com/8972182/47454370-55a6d880-d7cf-11e8-973c-45921b63dc94.png>

I haven't checked the source code yet, but maybe some dependencies need to be updated?

Thanks in advance, and I'm eager to start your course right now :-)
