### ISSUE TITLE
Asynchronous JavaScript (crossorigin.me)

### ISSUE THREAD

**Issue by Thenewteejay** [jonasschmedtmann/complete-javascript-course#86]
Just taking your complete JavaScript course. But find out that crossorigin.me for fetching is no accessible please how I can get the problem solve

**Comment by jonasschmedtmann** [comment]
Hi Thenewteejay,

Please post this question in the official course Q&A on Udemy, this is the central place for all questions, and makes this information available to all students of the course :)

--
Jonas Schmedtmann
jonas.io<http://jonas.io> / @jonasschmedtman<https://twitter.com/jonasschmedtman>

On July 15, 2020 at 4:09 PM, Thenewteejay (notifications@github.com<mailto:notifications@github.com>) wrote:
Just taking your complete JavaScript course. But find out that crossorigin.me for fetching is no accessible please how I can get the problem solve

**Comment by ricknaiamds** [comment]
> Just taking your complete JavaScript course. But find out that crossorigin.me for fetching is no accessible please how I can get the problem solve

**Comment by Thenewteejay** [comment]
> > Just taking your complete JavaScript course. But find out that crossorigin.me for fetching is no accessible please how I can get the problem solve

Cors-anywhere.herokuapp.com/
