### ISSUE TITLE
I tried to calculate tip by using switch/case method but the tips are getting calculated wrong. Can someone please check?

### ISSUE THREAD

**Issue by arvindsaxena92** [jonasschmedtmann/complete-javascript-course#98]
function tipcalculator(bill){

    switch(bill){
        case bill<50:
            return 0.2*bill;

            case bill>50 && bill<200:
                return 0.15*bill;

                default:
                    return 0.1*bill;
    }
}

console.log(tipcalculator(48));
console.log(tipcalculator(124));
console.log(tipcalculator(268));](url)`

**Comment by koayenay** [comment]
If you want to calculate tips using switch statement, it should be:

switch(true){
//code

}

**Comment by arvindsaxena92** [comment]
Thank you koayenay for replying.

**Comment by abhishekgl650** [comment]
hey @arvindsaxena92, can you please guide me through the source file so that I can work on this issue!
